## SORTING ALGORITHMS


#### Bubble Sort


In [ ]:
# bubble sort

import time as t


def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1, 0, -1):
        did_swap = False
        for j in range(i):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                did_swap = True
        if not did_swap:
            break
    return arr


start = t.time()

arr = [64, 34, 25, 12, 22, 11, 90]

print(bubble_sort(arr))


end = t.time()


print(f"Time taken: {end - start}")

# take input from user without loop

# arr = list(map(int, input().split()))

# print(bubble_sort(arr))

[11, 12, 22, 25, 34, 64, 90]
Time taken: 0.00019359588623046875


### Selection Sort


In [2]:
# selection sort

import time as t


def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]
    return arr


start = t.time()

arr = [64, 34, 25, 12, 22, 11, 90]
print(selection_sort(arr))

end = t.time()

print(f"Time taken: {end - start}")

[11, 12, 22, 25, 34, 64, 90]
Time taken: 0.00018787384033203125


### Insertion Sort


In [3]:
# insertion sort

import time as t


def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr


start = t.time()

arr = [64, 34, 25, 12, 22, 11, 90]

print(insertion_sort(arr))

end = t.time()

print(f"Time taken: {end - start}")

[11, 12, 22, 25, 34, 64, 90]
Time taken: 0.0012028217315673828


### Merge Sort


In [4]:
# merge sort

import time as t


def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left = arr[:mid]
        right = arr[mid:]

        merge_sort(left)
        merge_sort(right)

        i = j = k = 0

        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1

        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1
    return arr


start = t.time()

arr = [64, 34, 25, 12, 22, 11, 90]

print(merge_sort(arr))

end = t.time()

print(f"Time taken: {end - start}")

[11, 12, 22, 25, 34, 64, 90]
Time taken: 0.00013375282287597656


In [ ]:
# quick sort

import time as t


def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr.pop()
        left = []
        right = []
        for item in arr:
            if item < pivot:
                left.append(item)
            else:
                right.append(item)
        return quick_sort(left) + [pivot] + quick_sort(right)


start = t.time()

arr = [64, 34, 25, 12, 22, 11, 90]

print(quick_sort(arr))

end = t.time()

print(f"Time taken: {end - start}")

[11, 12, 22, 25, 34, 64, 90]
Time taken: 0.00013494491577148438


# pr 2


In [1]:
# Linear Search
def linearsearch(arr, target):
    n = len(arr)
    for index in range(n):
        if arr[index] == target:
            return index
    return -1


a = int(input("Enter How Many Element You Want To Enter: "))
b = []
for i in range(a):
    c = int(input("Enter Element"))
    b.append(c)
d = int(input("Enter Your Target"))
if d in b:
    e = linearsearch(b, d)
    print("In Array :", b, "Target :", d, "Was Found at index", e)
else:
    print("Invalid Choice")

In Array : [3, 5, 4, 2, 1] Target : 1 Was Found at index 4


In [ ]:
# Binary Search
def binarysearch(arr, low, high, x):
    if high >= low:
        mid = (high + low) // 2
        if arr[mid] == x:
            return mid
        elif arr[mid] > x:
            return binarysearch(arr, low, mid - 1, x)
        else:
            return binarysearch(arr, mid + 1, high, x)
    else:
        return -1


a = int(input("Enter How Many Element You Want To Enter: "))
b = []
for i in range(a):
    c = int(input("Enter Element"))
    b.append(c)
d = int(input("Enter Your Target"))
if d in b:
    e = binarysearch(b, 0, len(b) - 1, d)
    print("In Array :", b, "Target :", d, "Was Found At index", e)
else:
    print("Invalid Choice")

In Array : [1, 2, 3] Target : 3 Was Found At index 2


# pr 3


In [ ]:
# Adjacency List Undirected
graph = {}


def add_edge(graph, u, v):
    if u not in graph:
        graph[u] = []
    if v not in graph:
        graph[v] = []
    graph[u].append(v)
    graph[v].append(u)


add_edge(graph, "A", "B")
add_edge(graph, "A", "C")
add_edge(graph, "B", "A")
add_edge(graph, "B", "C")
add_edge(graph, "B", "D")
add_edge(graph, "C", "A")
add_edge(graph, "C", "B")
add_edge(graph, "C", "D")
add_edge(graph, "D", "B")
add_edge(graph, "D", "C")

for node in graph:
    print({node})
    print(graph[node])

{'A'}
['B', 'C', 'B', 'C']
{'B'}
['A', 'A', 'C', 'D', 'C', 'D']
{'C'}
['A', 'B', 'A', 'B', 'D', 'D']
{'D'}
['B', 'C', 'B', 'C']


In [ ]:
# Adjacency List Directed
graph = {}


def add_edge(graph, u, v):
    if u not in graph:
        graph[u] = []
        graph[u].append(v)
    if v not in graph:
        graph[v] = []


add_edge(graph, "A", "B")
add_edge(graph, "A", "C")
add_edge(graph, "B", "A")
add_edge(graph, "B", "C")
add_edge(graph, "B", "D")
add_edge(graph, "C", "A")
add_edge(graph, "C", "B")
add_edge(graph, "C", "D")
add_edge(graph, "D", "B")
add_edge(graph, "D", "C")

for node in graph:
    print({node})
    print(graph[node])

{'A'}
['B']
{'B'}
[]
{'C'}
[]
{'D'}
[]


In [ ]:
# Adjacency Matrix Undirected
import numpy as np

num_ver = 4
adj_matrix = np.zeros((num_ver, num_ver), dtype=int)
# print(adj_matrix)
edges = [(0, 1), (0, 2), (1, 2), (2, 3)]
for edge in edges:
    v1, v2 = edge
    adj_matrix[v1][v2] = 1
    adj_matrix[v2][v1] = 1
print(adj_matrix)

[[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]


In [ ]:
# Adjacency Matrix directed
import numpy as np

num_ver = 4
adj_matrix = np.zeros((num_ver, num_ver), dtype=int)
# print(adj_matrix)
edges = [(0, 1), (0, 2), (1, 2), (2, 3)]
for edge in edges:
    v1, v2 = edge
    adj_matrix[v1][v2] = 1
    # adj_matrix[v2][v1] = 1
print(adj_matrix)

[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


# pr 4


### BFS


In [ ]:
# BFS

graph = {"5": ["3", "7"], "3": ["2", "4"], "2": [], "4": [], "7": ["8"], "8": []}

visited = []
queue = []


def bfs(visited, graph, node):
    visited.append(node)
    queue.append(node)

    while queue:
        m = queue.pop(0)
        print(m, end=" ")

        for neighbour in graph[m]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)


print("BFS: ")
bfs(visited, graph, "5")

BFS: 
5 3 7 2 4 8 

In [ ]:
# DFS

graph = {"5": ["3", "7"], "3": ["2", "4"], "2": [], "4": [], "7": ["8"], "8": []}

visited = set()

def dfs(visited, graph, node):
    if node not in visited:
        print(node, end=" ")
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)


print("\nDFS: ")
dfs(visited, graph, "5")


DFS: 
5 3 2 4 7 8 

# pr 5


In [ ]:
# khruskal's algorithm


def find(parent, i):
    while parent[i] != i:
        i = parent[i]
    return i


def union(parent, rank, x, y):
    root_x = find(parent, x)
    root_y = find(parent, y)

    if root_x != root_y:
        if rank[root_x] > rank[root_y]:
            parent[root_y] = root_x
        elif rank[root_x] < rank[root_y]:
            parent[root_x] = root_y
        else:
            parent[root_y] = root_x
            rank[root_x] += 1


def kruskal(vertices, edges):
    edges.sort(key=lambda x: x[2])  # Sort edges by weight
    parent = list(range(vertices))  # Initially, each node is its own parent
    rank = [0] * vertices  # Initially, all nodes have rank 0
    mst = []  # To store the edges of the Minimum Spanning Tree

    for u, v, weight in edges:
        root_u = find(parent, u)
        root_v = find(parent, v)

        if root_u != root_v:
            mst.append((u, v, weight))  # Add this edge to the MST
            union(parent, rank, root_u, root_v)  # Union the two sets

    return mst


# Example usage:
vertices = 4
edges = [(0, 1, 10), (0, 2, 6), (0, 3, 5), (1, 3, 15), (2, 3, 4)]

mst = kruskal(vertices, edges)

print("Edges in mst: ")
for u, v, weight in mst:
    print(f"{u}-{v} with weight {weight}")

Edges in mst: 
2-3 with weight 4
0-3 with weight 5
0-1 with weight 10


In [2]:
# prim's algorithm


def prim(graph, vertices):
    mst = []
    in_mst = [False] * vertices
    key = [float("inf")] * vertices
    key[0] = 0
    parent = [-1] * vertices

    for _ in range(vertices):
        min_key = float("inf")
        u = -1

        for v in range(vertices):
            if not in_mst[v] and key[v] < min_key:
                min_key = key[v]
                u = v

        in_mst[u] = True

        if parent[u] != -1:
            mst.append([parent[u], u, key[u]])

        for v, weight in graph[u]:
            if not in_mst[v] and weight < key[v]:
                key[v] = weight
                parent[v] = u

    return mst


graph = {
    0: [(1, 9), (2, 5), (3, 4)],
    1: [(0, 9), (3, 14)],
    2: [(0, 4), (3, 5)],
    3: [(0, 5), (1, 14), (2, 5)],
}
vertices = 4

mst = prim(graph, vertices)

for u, v, weight in mst:
    print(f"Edge {u} - {v} with weight {weight}")

Edge 0 - 3 with weight 4
Edge 0 - 2 with weight 5
Edge 0 - 1 with weight 9


In [ ]:
# dijkstra algorithm

import heapq

def dijkstra(graph, start):
    distances = {node: float("infinity") for node in graph}
    distances[start] = 0
    pq = [(0, start)]
    while pq:
        current_distance, current_node = heapq.heappop(pq)
        if current_distance > distances[current_node]:
            continue
        for neighbor, weight in graph[current_node].items():
            distance = current_distance + weight
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(pq, (distance, neighbor))
    return distances


graph = {
    "A": {"B": 1, "C": 4},
    "B": {"A": 1, "C": 2, "D": 5},
    "C": {"A": 4, "B": 2, "D": 1},
    "D": {"B": 5, "C": 1},
}

print(dijkstra(graph, "A"))

{'A': 0, 'B': 1, 'C': 3, 'D': 4}


In [ ]:
# bellman ford algorithm

def bellman_ford(graph, vertices, source):
    distance = [float("infinity")] * vertices
    distance[source] = 0
    for _ in range(vertices - 1):
        for u, v, w in graph:
            if distance[u] != float("infinity") and distance[u] + w < distance[v]:
                distance[v] = distance[u] + w
    for u, v, w in graph:
        if distance[u] != float("infinity") and distance[u] + w < distance[v]:
            print("Graph contains negative weight cycle")
            return
    for i in range(vertices):
        print(f"Distance from source to {i} is {distance[i]}")


graph = [
    (1, 2, 2),
    (1, 3, 4),
    (2, 3, 1),
    (2, 4, 7),
    (3, 5, 3),
    (4, 6, 1),
    (5, 4, 2),
    (5, 6, 5),
]
bellman_ford(graph, 7, 1)

Distance from source to 0 is inf
Distance from source to 1 is 0
Distance from source to 2 is 2
Distance from source to 3 is 3
Distance from source to 4 is 8
Distance from source to 5 is 6
Distance from source to 6 is 9


In [1]:
# knapsack problem
def fractional_knapsack(capacity, items):
    items.sort(key=lambda x: x[1] / x[0], reverse=True)
    total_value = 0
    for weight, profit in items:
        if capacity > 0:
            if weight <= capacity:
                capacity -= weight
                total_value += profit
            else:
                total_value += profit * (capacity / weight)
                capacity = 0
                break
    return total_value


items = [(10, 60), (20, 100), (30, 120)]
capacity = 50
print(fractional_knapsack(capacity, items))

240.0


In [ ]:
# 0 1 knapsack problem


def knapsack(values, weights, capacity):
    n = len(values)
    dp = [[0] * (capacity + 1) for _ in range(n + 1)]
    for i in range(1, n + 1):
        for w in range(1, capacity + 1):
            if weights[i - 1] <= w:
                dp[i][w] = max(
                    dp[i - 1][w], values[i - 1] + dp[i - 1][w - weights[i - 1]]
                )
            else:
                dp[i][w] = dp[i - 1][w]

    for row in dp:
        print(row)

    return dp[n][capacity]


values = [12, 10, 20, 15]
weights = [2, 1, 3, 2]
capacity = 5

max_value = knapsack(values, weights, capacity)
print(f"max value: {max_value}")

[0, 0, 0, 0, 0, 0]
[0, 0, 12, 12, 12, 12]
[0, 10, 12, 22, 22, 22]
[0, 10, 12, 22, 30, 32]
[0, 10, 15, 25, 30, 37]
max value: 37


In [ ]:
# heap sort (max heap)

def max_heap(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2
    if left < n and arr[left] > arr[largest]:
        largest = left
    if right < n and arr[right] > arr[largest]:
        largest = right
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        max_heap(arr, n, largest)


def heap_sort(arr):
    n = len(arr)
    for i in range(n // 2 - 1, -1, -1):
        max_heap(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        max_heap(arr, i, 0)
    return arr


arr = [12, 11, 13, 5, 6, 7]

print(heap_sort(arr))

# heap sort (min heap)

def min_heap(arr, n, i):
    smallest = i
    left = 2 * i + 1
    right = 2 * i + 2
    if left < n and arr[left] < arr[smallest]:
        smallest = left
    if right < n and arr[right] < arr[smallest]:
        smallest = right
    if smallest != i:
        arr[i], arr[smallest] = arr[smallest], arr[i]
        min_heap(arr, n, smallest)


def heap_sort(arr):
    n = len(arr)
    for i in range(n // 2 - 1, -1, -1):
        min_heap(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        min_heap(arr, i, 0)
    return arr

arr = [12, 11, 13, 5, 6, 7]

print(heap_sort(arr))

[5, 6, 7, 11, 12, 13]
[13, 12, 11, 7, 6, 5]


In [ ]:
# ith order statistics (quick select)

import random

def quick_select(arr, k):
    if len(arr) == 1:
        return arr[0]
    pivot = random.choice(arr)
    left = [x for x in arr if x < pivot]
    mid = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    if k < len(left):
        return quick_select(left, k)
    elif k < len(left) + len(mid):
        return mid[0]
    else:
        return quick_select(right, k - len(left) - len(mid))

arr = [12, 11, 13, 5, 6, 7]

k = 2

print(f"The {k+1} th smallest element is {quick_select(arr,k)}")

The 3 th smallest element is 7


In [ ]:
# n queen problem

def is_safe(board, row, col, n):
    # Check column
    for i in range(row):
        if board[i][col] == 1:
            return False

    # Check upper-left diagonal
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    # Check upper-right diagonal
    for i, j in zip(range(row, -1, -1), range(col, n)):
        if board[i][j] == 1:
            return False

    return True

def solve_n_queen(board, row, n):
    if row >= n:  # All queens are placed
        return True

    for col in range(n):  # Try all columns in the current row
        if is_safe(board, row, col, n):
            board[row][col] = 1  # Place the queen
            if solve_n_queen(board, row + 1, n):  # Recur for the next row
                return True
            board[row][col] = 0  # Backtrack

    return False

def n_queen(n):
    board = [[0 for _ in range(n)] for _ in range(n)]  # Initialize board
    if not solve_n_queen(board, 0, n):
        print("No solution exists")
    else:
        for row in board:
            print(row)

# Test with 4 queens
n = 4
n_queen(n)


[0, 1, 0, 0]
[0, 0, 0, 1]
[1, 0, 0, 0]
[0, 0, 1, 0]
